// Code generated by protoc-gen-go. DO NOT EDIT.
// Regenerate with: protoc --go_out=. --go-grpc_out=. proto/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------------------------
// IndexRepository
// ---------------------------------------------------------------------------

type IndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoId string         `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Files  []*FileContent `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *IndexRequest) Reset()         { *x = IndexRequest{} }
func (x *IndexRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *IndexRequest) ProtoMessage()  {}

func (x *IndexRequest) ProtoReflect() protoreflect.Message {
	return nil // simplified stub
}

func (x *IndexRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *IndexRequest) GetFiles() []*FileContent {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content  string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Language string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *FileContent) Reset()         { *x = FileContent{} }
func (x *FileContent) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *FileContent) ProtoMessage()  {}
func (x *FileContent) ProtoReflect() protoreflect.Message { return nil }

func (x *FileContent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileContent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type IndexResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ChunksIndexed int32  `protobuf:"varint,2,opt,name=chunks_indexed,json=chunksIndexed,proto3" json:"chunks_indexed,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *IndexResponse) Reset()         { *x = IndexResponse{} }
func (x *IndexResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *IndexResponse) ProtoMessage()  {}
func (x *IndexResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *IndexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexResponse) GetChunksIndexed() int32 {
	if x != nil {
		return x.ChunksIndexed
	}
	return 0
}

func (x *IndexResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ---------------------------------------------------------------------------
// Chat
// ---------------------------------------------------------------------------

type ChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoId  string         `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId  string         `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	History []*ChatMessage `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
}

func (x *ChatRequest) Reset()         { *x = ChatRequest{} }
func (x *ChatRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ChatRequest) ProtoMessage()  {}
func (x *ChatRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *ChatRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role    string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatMessage) Reset()         { *x = ChatMessage{} }
func (x *ChatMessage) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ChatMessage) ProtoMessage()  {}
func (x *ChatMessage) ProtoReflect() protoreflect.Message { return nil }

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Done       bool       `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	References []*FileRef `protobuf:"bytes,3,rep,name=references,proto3" json:"references,omitempty"`
}

func (x *ChatChunk) Reset()         { *x = ChatChunk{} }
func (x *ChatChunk) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ChatChunk) ProtoMessage()  {}
func (x *ChatChunk) ProtoReflect() protoreflect.Message { return nil }

func (x *ChatChunk) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetReferences() []*FileRef {
	if x != nil {
		return x.References
	}
	return nil
}

type FileRef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath  string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	StartLine int32  `protobuf:"varint,2,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine   int32  `protobuf:"varint,3,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
}

func (x *FileRef) Reset()         { *x = FileRef{} }
func (x *FileRef) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *FileRef) ProtoMessage()  {}
func (x *FileRef) ProtoReflect() protoreflect.Message { return nil }

func (x *FileRef) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileRef) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *FileRef) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

// ---------------------------------------------------------------------------
// SearchSimilar
// ---------------------------------------------------------------------------

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RepoId string `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	TopK   int32  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
}

func (x *SearchRequest) Reset()         { *x = SearchRequest{} }
func (x *SearchRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchRequest) ProtoMessage()  {}
func (x *SearchRequest) ProtoReflect() protoreflect.Message { return nil }

func (x *SearchRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *SearchResponse) Reset()         { *x = SearchResponse{} }
func (x *SearchResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchResponse) ProtoMessage()  {}
func (x *SearchResponse) ProtoReflect() protoreflect.Message { return nil }

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId   string  `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	FilePath  string  `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Content   string  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score     float32 `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	StartLine int32   `protobuf:"varint,5,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine   int32   `protobuf:"varint,6,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	ChunkType string  `protobuf:"bytes,7,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"`
	Name      string  `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchResult) Reset()         { *x = SearchResult{} }
func (x *SearchResult) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *SearchResult) ProtoMessage()  {}
func (x *SearchResult) ProtoReflect() protoreflect.Message { return nil }

func (x *SearchResult) GetChunkId() string   { return x.ChunkId }
func (x *SearchResult) GetFilePath() string  { return x.FilePath }
func (x *SearchResult) GetContent() string   { return x.Content }
func (x *SearchResult) GetScore() float32    { return x.Score }
func (x *SearchResult) GetStartLine() int32  { return x.StartLine }
func (x *SearchResult) GetEndLine() int32    { return x.EndLine }
func (x *SearchResult) GetChunkType() string { return x.ChunkType }
func (x *SearchResult) GetName() string      { return x.Name }

// Ensure these types satisfy proto.Message interface (compile-time check)
var (
	_ protoreflect.ProtoMessage = (*IndexRequest)(nil)
	_ protoreflect.ProtoMessage = (*IndexResponse)(nil)
	_ protoreflect.ProtoMessage = (*FileContent)(nil)
	_ protoreflect.ProtoMessage = (*ChatRequest)(nil)
	_ protoreflect.ProtoMessage = (*ChatMessage)(nil)
	_ protoreflect.ProtoMessage = (*ChatChunk)(nil)
	_ protoreflect.ProtoMessage = (*FileRef)(nil)
	_ protoreflect.ProtoMessage = (*SearchRequest)(nil)
	_ protoreflect.ProtoMessage = (*SearchResponse)(nil)
	_ protoreflect.ProtoMessage = (*SearchResult)(nil)
)

// register types for protobuf reflection
var _ = sync.Once{}
var _ = reflect.TypeOf
