// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// Regenerate with: protoc --go_out=. --go-grpc_out=. proto/ai/ai.proto

package ai

import (
	"context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// AIServiceClient is the client API for AIService service.
type AIServiceClient interface {
	IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIService_ChatClient, error)
	SearchSimilar(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) IndexRepository(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := c.cc.Invoke(ctx, "/ai.AIService/IndexRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (AIService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &AIService_ServiceDesc.Streams[0], "/ai.AIService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &aIServiceChatClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AIService_ChatClient interface {
	Recv() (*ChatChunk, error)
	grpc.ClientStream
}

type aIServiceChatClient struct {
	grpc.ClientStream
}

func (x *aIServiceChatClient) Recv() (*ChatChunk, error) {
	m := new(ChatChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aIServiceClient) SearchSimilar(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/ai.AIService/SearchSimilar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
type AIServiceServer interface {
	IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error)
	Chat(*ChatRequest, AIService_ChatServer) error
	SearchSimilar(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) IndexRepository(context.Context, *IndexRequest) (*IndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexRepository not implemented")
}

func (UnimplementedAIServiceServer) Chat(*ChatRequest, AIService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func (UnimplementedAIServiceServer) SearchSimilar(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSimilar not implemented")
}

func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_IndexRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).IndexRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIService/IndexRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).IndexRepository(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIServiceServer).Chat(m, &aIServiceChatServer{stream})
}

type AIService_ChatServer interface {
	Send(*ChatChunk) error
	grpc.ServerStream
}

type aIServiceChatServer struct {
	grpc.ServerStream
}

func (x *aIServiceChatServer) Send(m *ChatChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _AIService_SearchSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SearchSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIService/SearchSimilar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SearchSimilar(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexRepository",
			Handler:    _AIService_IndexRepository_Handler,
		},
		{
			MethodName: "SearchSimilar",
			Handler:    _AIService_SearchSimilar_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ai/ai.proto",
}
